### ISSUE TITLE
Can't save world on satisfactory server

### ISSUE THREAD

**Issue by Bear-Creator** [ghostcap-gaming/pterodactyl-eggs#1]
I can't save satisfactory server, The error is "failed to save game couldn't write file to disk server" in game and "Warning: open('/home/container/.config/Epic/FactoryGame/Saved/SaveGames/server/321.sav', Flags=0x00080041) failed: errno=13 (Permission denied)" in console.

**Comment by pedrotski** [comment]
This is something you would need to ask in the Satisfactory Discord. It's not related to the egg as that doesn't control anything related to the reading or writing of files while the game is running, sorry.
